# Generated by Django 4.0.1 on 2022-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=100, null=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
