# Generated by Django 4.0.1 on 2022-02-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='abc',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
